### ISSUE TITLE
Latest Pull ALTER TABLE payment Error +  PayTo: pq: unexpected Parse response 'C'

### ISSUE THREAD

**Issue by qlpqlp** [dogecoinfoundation/gigawallet#123]
There is a bug on the migration because its not compatible with the latest version of PostgreSQL version on type numeric that does not allow NOT NULL

Fix  SQL Migration from v0.1.0-beta2 to v0.1.1

Change:
`ALTER TABLE payment ADD COLUMN total NUMERIC(18,8) NOT NULL;`

To:
`ALTER TABLE payment ADD COLUMN total NUMERIC(18,8) DEFAULT 0;`

After that Im getting the error, still did not debugged why

`2023/10/27 17:42:18 BalanceKeeper: ListPayments 'DDrHK26acgqY2f4bsSNR1bCyfcatmt8zP6': PostgresStore error: getPaymentOutputs: querying PayTo: pq: unexpected Parse response 'C'`

**Comment by raffecat** [comment]
I checked the Postgres docs, and I can't find anything saying a NUMERIC column cannot be NOT NULL, however, it's true that this will not work if you have any rows in the table (since in that case the added column would have NULL values)

I've re-written the migration now, because it actually didn't attempt to migrate existing data, which means it's not very useful as a migration.
